# Generated by Django 5.1.2 on 2024-11-22 09:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('petcareapp', '0002_tenant'),
    ]

    operations = [
        migrations.CreateModel(
            name='PetAdoptionApplication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('application_date', models.DateField()),
                ('adoption_status', models.CharField(max_length=50)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='petcareapp.customer')),
                ('pet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='petcareapp.pet')),
            ],
        ),
        migrations.CreateModel(
            name='PetCarePayment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('payment_date', models.DateField()),
                ('pet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='petcareapp.pet')),
            ],
        ),
        migrations.DeleteModel(
            name='Tenant',
        ),
    ]
